--- 
engines: 
  eslint: 
    channel: eslint-2
    config: 
      extensions: 
        - .es6
        - .js
    enabled: true
exclude_paths: 
  - test/*
  - dist/*
  - bower_components/*
  - node_modules/*
  - app/_components/*
languages: 
  JavaScript: true
ratings: 
  paths: 
    - app/**
    - "**.js"
